cout<<"MENU\n";
		cout<<"0. Imprimir de izquierda a derecha\n";
		cout<<"1. Imprimir de derecha a izquierda\n";
		cout<<"2. Insertar a la derecha\n";
		cout<<"3. Insertar a la izquierda\n";
		cout<<"4. Insertar aleatorios al inicio\n";
		cout<<"5. Insertar aleatorios al final\n";
		cout<<"6. Busqueda\n";
		cout<<"7. Sumar datos\n";
		cout<<"8. Insertar antes de X\n";
		cout<<"9. Insertar despues de X\n";
		cout<<"10.Insertar cada N nodos X\n";
		cout<<"11.Modificar X\n";
		cout<<"12.Eliminar inicio\n";
		cout<<"13.Eliminar final\n";
		cout<<"14.Eliminar antes de X\n";
		cout<<"15.Eliminar despues de X\n";
		cout<<"16.Eliminar un bloque al inicio\n";
		cout<<"17.Eliminar del dato X al dato Y\n";
		cout<<"18. Burbuja\n";
